vich_uploader:
    db_driver: orm

    mappings:
       products_images:
           uri_prefix: '%product_images%'
           upload_destination: '%kernel.project_dir%/public%product_images%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: false
